---
- name: Deploy Docker Container
  hosts: webservers
  become: true

  vars:
    ecr_url: "500345929326.dkr.ecr.ap-southeast-2.amazonaws.com"
    image_name: "devops-project"
    image_tag: "latest"

  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Login to ECR
      shell: |
        aws ecr get-login-password \
          --region ap-southeast-2 | \
          docker login \
          --username AWS \
          --password-stdin {{ ecr_url }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"

    - name: Pull Docker image from ECR
      shell: |
        docker pull {{ ecr_url }}/{{ image_name }}:{{ image_tag }}

    - name: Stop old container
      shell: docker stop myapp || true

    - name: Remove old container
      shell: docker rm myapp || true

    - name: Run new container
      shell: |
        docker run -d \
          --name myapp \
          -p 80:80 \
          {{ ecr_url }}/{{ image_name }}:{{ image_tag }}

    - name: Verify container running
      shell: docker ps
      register: docker_status

    - name: Print status
      debug:
        msg: "Container is running! 🎉"